INSERT INTO club (id, name, address, shortName) VALUES (1, 'Firebrands', 'Longwood, Clevedon Road, Failand, Bristol BS8 3TL', 'FHC');
INSERT INTO club (id, name, address, shortName) VALUES (2, 'Bristol City', 'Ashton Rd, Bristol BS3 2EJ', 'BCFC');
INSERT INTO club (id, name, address, shortName) VALUES (3, 'Liverpool Football Club', 'Ashton Rd, Bristol BS3 2EJ', 'LFC');
INSERT INTO club (id, name, address, shortName) VALUES (4, 'Beeston Hockey Club', 'Highfields Park, University Blvd, Nottingham NG7 2PS', 'BHC');
INSERT INTO team (id, name, league, gender, age_range, clubId) VALUES (1, 'First Team', 0, 0, 1, 1);
INSERT INTO team (id, name, league, gender, age_range, clubId) VALUES (2, 'Second Team', 1, 0, 1, 1);
INSERT INTO team (id, name, league, gender, age_range, clubId) VALUES (3, 'First Team', 0, 1, 1, 2);
INSERT INTO player (id, name, address, email, teamId) VALUES (1, 'Ellie Hield', 'Awesome Road 1', 'ehield@scottlogic.com', 1);
INSERT INTO player (id, name, address, email, teamId) VALUES (2, 'Matt Smith', 'Eurovision Road 22', 'msmith@scottlogic.com', 1);
INSERT INTO player (id, name, address, email, teamId) VALUES (3, 'Daniel Lucas', 'Royal Oak Road 54', 'dalucas@scottlogic.com', 1);
INSERT INTO player (id, name, address, email, teamId) VALUES (4, 'Matt Cline', 'Kings Cross 99', 'mcline@scottlogic.com', 2);
INSERT INTO player (id, name, address, email, teamId) VALUES (5, 'Sarah Haswell', 'Castle Park 420', 'shaswell@scottlogic.com', 2);
INSERT INTO player (id, name, address, email, teamId) VALUES (6, 'Norman the Badger', 'River Avon 7', 'nbadger@scottlogic.com', 2);