INSERT INTO club (id, name, address, shortName) VALUES (1, 'Firebrands', 'Longwood, Clevedon Road, Failand, Bristol BS8 3TL', 'FHC');
INSERT INTO club (id, name, address, shortName) VALUES (2, 'Bristol City', 'Ashton Rd, Bristol BS3 2EJ', 'BCFC');
INSERT INTO club (id, name, address, shortName) VALUES (3, 'Liverpool Football Club', 'Ashton Rd, Bristol BS3 2EJ', 'LFC');
INSERT INTO club (id, name, address, shortName) VALUES (4, 'Beeston Hockey Club', 'Highfields Park, University Blvd, Nottingham NG7 2PS', 'BHC');
INSERT INTO club (id, name) VALUES (5, 'Club 5');
INSERT INTO team (id, name, clubId, address, short_name, league) VALUES (1, 'Team Amazing', 1, 'Redcliff Street 1, BS1', 'TA', 'South West Coconut Tree League');
INSERT INTO team (id, name, clubId) VALUES (2, 'Matt Team 1', 1);
INSERT INTO team (id, name, clubId) VALUES (3, 'Bad Team', 2);
INSERT INTO player (id, name) VALUES (1, 'Ellie Hield');
INSERT INTO player (id, name) VALUES (2, 'Matt Smith');
INSERT INTO player (id, name) VALUES (3, 'Daniel Lucas');